import "./globals.css";
import { Inder } from 'next/font/google'

const inder = Inder({
  subsets: ['latin'],
  weight: '400', // Inder only has 400
  display: 'swap',
})
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${inder.className} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
